Repository master-csmi/csmi-stages-2024, pull requests merged in 2024-08, with the labels that each got.

#2 update documentation
  .gitignore
  antora.yml
  modules/ROOT/images/netlify-deploy-preview.png
  modules/ROOT/pages/index.adoc
  netlify-build.sh
  netlify.toml
  package-lock.json
  package.json
  site.yml
Labels: enhancement

#5 Slide and report Geraldes Pereira Dorian
  modules/m1/partials/rapports.adoc
Labels: M1, Soutenances, Stages, documentation

#26 #25
  modules/m1/attachments/Zaouache-Narimane-slides.pdf
Labels: M1

#24 Ajout du slides Bouhenniche Oussama
  modules/m1/attachments/Bouhenniche-Oussama-slides.pdf
Labels: M1, Stages

#22 adding slide
  modules/m1/attachments/Geraldes-Pereira-Dorian-slides.pdf
  modules/m1/partials/rapports.adoc
Labels: M1, Soutenances, Stages, documentation

#21 Antora Report Carpi Lapi
  modules/m1/partials/rapports.adoc
Labels: documentation

#34 mettre a jour slides
  modules/m1/attachments/Zaouache-Narimane-slides.pdf
Labels: M1

#31 M1 dieng
  modules/m1/attachments/Dieng-Adama-slides.pdf
  modules/m1/attachments/Dieng-adama-slides.pdf
Labels: M1
